INSERT INTO EMPLOYEE  VALUES (1, 0,'Warrior','red');
INSERT INTO EMPLOYEE  VALUES (2, 0,'Wizard','green');
INSERT INTO EMPLOYEE  VALUES (3, 0,'Priest','white');
INSERT INTO EMPLOYEE  VALUES (4, 0,'Rogue','yellow');
INSERT INTO EMPLOYEE  VALUES (5, 1,'Fighter','blue');
INSERT INTO EMPLOYEE  VALUES (6, 1,'Paladin','lightblue');
INSERT INTO EMPLOYEE  VALUES (7, 1,'Ranger','lightgreen');
INSERT INTO EMPLOYEE  VALUES (8, 2,'Mage','grey');
INSERT INTO EMPLOYEE  VALUES (9, 2,'Specialist wizard','lightgrey');
INSERT INTO EMPLOYEE  VALUES (10, 3,'Cleric','red');
INSERT INTO EMPLOYEE  VALUES (11, 3,'Druid','green');
INSERT INTO EMPLOYEE  VALUES (12, 3,'Priest of specific mythos','white');
INSERT INTO EMPLOYEE  VALUES (13, 4,'Thief','yellow');
INSERT INTO EMPLOYEE  VALUES (14, 4,'Bard','blue');
INSERT INTO EMPLOYEE  VALUES (15, 13,'Assassin','lightblue');